### ISSUE TITLE
VDR 2.3.x

### ISSUE THREAD

**Issue by friedl82** [pipelka/vdr-plugin-robotv#4]
Do you have plans to make the plugin compatible with the new vdr dev version?

**Comment by pipelka** [comment]
Hi,

Thats definitely on my todo. Unfortunately there's a big lack of time, ...
But I'm pretty sure to support the 2.3.x version in the near future (no
timeframe).

Regards,
Alex


2017-07-30 8:55 GMT+02:00 friedl82 <notifications@github.com>:

**Comment by tunip** [comment]
friedl82 was faster. Just for your info:
https://www.vdr-portal.de/forum/index.php?thread/130924-robotv-plugin-f%C3%BCr-vdr-2-3-x/&postID=1295278#post1295278

**Comment by pipelka** [comment]
Alright. Here is an experimental version for VDR 2.3.x (tested with 2.3.8):
https://github.com/pipelka/vdr-plugin-robotv/tree/dev-vdr-2.3.x

The following things should work:
* Recordings / Playback of recordings
* EPG
* Timers (Create / Delete)

LiveTV is completely untested because my production system runs VDR 2.2.0.

Feedback is highly appreciated.
BTW, the latest "master" of the client is probably needed to get it working.

**Comment by tunip** [comment]
Live TV woks fine here with dev-vdr-2.3.x. I am using latest "master" on the client.

**Comment by pipelka** [comment]
Good news. Does it also work with encrypted channels ?

**Comment by tunip** [comment]
Yes, it works also with encrypted channels. Thx for the experimental version at this point 👍

**Comment by friedl82** [comment]
Great. This are good news. I will be able to test it next week also with decrypted channels. I'm at holiday at the moment.

**Comment by tunip** [comment]
Still working fine. Only the logs fill up with this entrys::
 `vdr: [10] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'`

https://stackoverflow.com/questions/31072074/unable-to-start-simple-transaction-in-sqlite

I deleted the storage.db, storage.db-shm & storage.db-wal files but it still floods the log.

I am not sure if this is related to this experimental version. Have to test it with VDR 2.2 too.

**Comment by pipelka** [comment]
It seems in VDR 2.3 the semantics of the functions:
* cEpgHandler::BeginSegmentTransfer
* cEpgHandler::EndSegmentTransfer

have changed.

Thanks. I will check that.

**Comment by pipelka** [comment]
Just another thought:
Are you using other plugins processing epg data ?
Please try to load the robotv plugin as the very first one.

**Comment by tunip** [comment]
I am loading robotv before other plugins like epgsearch & streamdev-server. No other epg data processing plugins used.

Startup of VDR only with the robotv plugin (disabled temporary all other plugins).
If the first EPG data is delivered, it starts flooding.
```
user.info:Aug 17 08:53:51 vdr: [40] VDR version 2.3.8 started
user.info:Aug 17 08:53:51 vdr: [40] codeset is 'UTF-8' - known
user.info:Aug 17 08:53:51 vdr: [40] override character table is 'ISO-8859-15'
user.info:Aug 17 08:53:51 vdr: [40] loading plugin: /usr/lib/vdr/libvdr-robotv.so.2.3.8
user.info:Aug 17 08:53:51 vdr: [40] loading /config/etc/setup.conf
user.info:Aug 17 08:53:51 vdr: [40] loading /config/etc/sources.conf
user.info:Aug 17 08:53:51 vdr: [40] loading /config/etc/diseqc.conf
user.info:Aug 17 08:53:51 vdr: [40] loading /config/etc/scr.conf
user.info:Aug 17 08:53:51 vdr: [40] loading /config/etc/channels.conf
user.info:Aug 17 08:53:51 vdr: [40] loading /config/etc/timers.conf
user.info:Aug 17 08:53:51 vdr: [40] loading /config/etc/svdrphosts.conf
user.info:Aug 17 08:53:51 vdr: [40] loading /config/etc/remote.conf
user.info:Aug 17 08:53:51 vdr: [40] loading /config/etc/keymacros.conf
user.info:Aug 17 08:53:51 vdr: [40] DVB API version is 0x050A (VDR was built with 0x050A)
user.info:Aug 17 08:53:51 vdr: [40] frontend 0/0 provides DVB-S,DVB-S2,DSS with QPSK ("STV0910")
user.info:Aug 17 08:53:51 vdr: [40] frontend 1/0 provides DVB-S,DVB-S2,DSS with QPSK ("STV0910")
user.info:Aug 17 08:53:51 vdr: [40] frontend 2/0 provides DVB-S,DVB-S2,DSS with QPSK ("STV0910")
user.info:Aug 17 08:53:51 vdr: [40] frontend 3/0 provides DVB-S,DVB-S2,DSS with QPSK ("STV0910")
user.info:Aug 17 08:53:51 vdr: [40] found 4 DVB devices
user.info:Aug 17 08:53:51 vdr: [40] initializing plugin: robotv (0.10.3): roboTV Server
user.info:Aug 17 08:53:51 vdr: [40] loading /config/etc/plugins/robotv/robotv.conf
user.info:Aug 17 08:53:51 vdr: [40] timeshift buffersize: 8000000000 bytes
user.info:Aug 17 08:53:51 vdr: [40] Folder for TV shows: Serien
user.info:Aug 17 08:53:51 vdr: [40] Channel cache enabled: no
user.info:Aug 17 08:53:51 vdr: [40] setting primary device to 1
user.info:Aug 17 08:53:51 vdr: [40] device 1 has no MPEG decoder
user.info:Aug 17 08:53:51 vdr: [40] setting current skin to "classic"
user.info:Aug 17 08:53:51 vdr: [40] loading /config/etc/themes/classic-default.theme
user.info:Aug 17 08:53:51 vdr: [40] starting plugin: robotv
user.info:Aug 17 08:53:51 vdr: [40] Opening database: /config/cache/plugins/robotv/storage.db
user.err:Aug 17 08:53:51 vdr: [40] ERROR: no OSD provider available - using dummy OSD!
user.info:Aug 17 08:53:51 vdr: [51] Opening database: /config/cache/plugins/robotv/storage.db
user.info:Aug 17 08:53:51 vdr: [51] removing outdated artwork
user.info:Aug 17 08:53:51 vdr: [51] removing outdated epg entries
user.info:Aug 17 08:53:51 vdr: [51] Requesting clients to reload recordings list
user.info:Aug 17 08:53:51 vdr: [51] roboTV Server started
user.info:Aug 17 08:53:54 vdr: [51] loading /config/etc/plugins/robotv/allowed_hosts.conf
user.info:Aug 17 08:53:54 vdr: [51] Client 10.10.10.31:53688 with ID 0 connected.
user.info:Aug 17 08:53:54 vdr: [53] Welcome client 'roboTV:dataservice' with protocol version '7' and priority 1
user.info:Aug 17 08:53:54 vdr: [51] loading /config/etc/plugins/robotv/allowed_hosts.conf
user.info:Aug 17 08:53:54 vdr: [51] Client 10.10.10.32:8387 with ID 1 connected.
user.info:Aug 17 08:53:54 vdr: [54] Welcome client 'roboTV:dataservice' with protocol version '7' and priority 1
user.info:Aug 17 08:54:01 vdr: [40] switching to channel 1 S19.2E-1-1019-10301 (Das Erste HD)
user.info:Aug 17 08:54:01 vdr: [55] SVDRP listening on port 6419/tcp
user.err:Aug 17 08:54:01 vdr: [40] ERROR: no OSD provider available - using dummy OSD!
user.err:Aug 17 08:54:03 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:04 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:04 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:04 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:05 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:05 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:05 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:06 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:06 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:06 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:07 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:07 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:07 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:08 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:08 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:08 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
user.err:Aug 17 08:54:09 vdr: [44] SQLite: cannot start a transaction within a transaction on statement 'BEGIN;'
...
```

**Comment by pipelka** [comment]
Ok. I added some transaction locking to handle this case.
Please repull the "dev-vdr-2.3.x" branch (was rebased on top of "dev").

**Comment by tunip** [comment]
No syslog flooding but Live TV does not work.

A few reconnects in the Log and the message in Live Channles "Fehler: Kanal kann nicht wiedergegeben werden" and a few seconds later "Fehler: Wiedergabefehler".

```
Aug 17 21:54:22 f44b82a77fcb vdr: [22] loading /config/etc/plugins/robotv/allowed_hosts.conf
Aug 17 21:54:22 f44b82a77fcb vdr: [22] Client 10.10.10.31:18850 with ID 0 connected.
Aug 17 21:54:22 f44b82a77fcb vdr: [38] Welcome client 'roboTV:dataservice' with protocol version '7' and priority 1
Aug 17 21:54:23 f44b82a77fcb vdr: [22] loading /config/etc/plugins/robotv/allowed_hosts.conf
Aug 17 21:54:23 f44b82a77fcb vdr: [22] Client 10.10.10.32:35532 with ID 1 connected.
Aug 17 21:54:23 f44b82a77fcb vdr: [39] Welcome client 'roboTV:dataservice' with protocol version '7' and priority 1
Aug 17 21:54:24 f44b82a77fcb vdr: [22] loading /config/etc/plugins/robotv/allowed_hosts.conf
Aug 17 21:54:24 f44b82a77fcb vdr: [22] Client 10.10.10.31:19106 with ID 2 connected.
Aug 17 21:54:24 f44b82a77fcb vdr: [40] Welcome client 'roboTV:streaming' with protocol version '7' and priority 7
Aug 17 21:54:24 f44b82a77fcb vdr: [40] Preferred language: deu / type: 2
Aug 17 21:54:47 f44b82a77fcb vdr: [22] loading /config/etc/plugins/robotv/allowed_hosts.conf
Aug 17 21:54:47 f44b82a77fcb vdr: [22] Client 10.10.10.31:19618 with ID 3 connected.
Aug 17 21:54:47 f44b82a77fcb vdr: [42] Welcome client 'roboTV:streaming' with protocol version '7' and priority 7
Aug 17 21:54:47 f44b82a77fcb vdr: [42] Preferred language: deu / type: 2
```

**Comment by tunip** [comment]
Refetching channels in Live Channels app results in this messages no channels in the list (Keine Kanäle verfügbar).

```
Aug 17 22:00:11 f44b82a77fcb vdr: [22] loading /config/etc/plugins/robotv/allowed_hosts.conf
Aug 17 22:00:11 f44b82a77fcb vdr: [22] Client 10.10.10.31:19874 with ID 4 connected.
Aug 17 22:00:11 f44b82a77fcb vdr: [43] Welcome client 'AndroidTV Settings' with protocol version '7' and priority 7
Aug 17 22:00:11 f44b82a77fcb vdr: [43] Opening database: /config/cache/plugins/robotv/storage.db
Aug 17 22:00:11 f44b82a77fcb vdr: [43] Fetching channels ...
Aug 17 22:00:11 f44b82a77fcb vdr: [43] Type: MPEG2/H.264 channels
Aug 17 22:00:11 f44b82a77fcb vdr: [43] Free To Air channels: Yes
Aug 17 22:00:11 f44b82a77fcb vdr: [43] Only native language: No
Aug 17 22:00:11 f44b82a77fcb vdr: [43] Enabled CaIDs: 
Aug 17 22:00:14 f44b82a77fcb vdr: [22] loading /config/etc/plugins/robotv/allowed_hosts.conf
Aug 17 22:00:14 f44b82a77fcb vdr: [22] Client 10.10.10.31:20130 with ID 5 connected.
Aug 17 22:00:14 f44b82a77fcb vdr: [44] Welcome client 'roboTV Sync Adapter' with protocol version '7' and priority 1
Aug 17 22:00:14 f44b82a77fcb vdr: [44] Fetching channels ...
Aug 17 22:00:14 f44b82a77fcb vdr: [44] Type: MPEG2/H.264 channels
Aug 17 22:00:14 f44b82a77fcb vdr: [44] Free To Air channels: Yes
Aug 17 22:00:14 f44b82a77fcb vdr: [44] Only native language: No
Aug 17 22:00:14 f44b82a77fcb vdr: [44] Enabled CaIDs: 
```

**Comment by pipelka** [comment]
Very strange. But obviously a locking issue (but working with VDR 2.2).
Ok. I temporarily removed the locking and transaction stuff.
Please repull the branch.

**Comment by tunip** [comment]
Looks good now, thx. No syslog flooding and working Live TV.

**Comment by pipelka** [comment]
Thanks. Nevertheless i have to find a solution for the transaction problem.

**Comment by tunip** [comment]
Can you check EPG update in your dev environment? After a few days I am missing EPG in Live Channels. Thx

**Comment by pipelka** [comment]
The backported transaction locking may cause this. Will check in the evening when at home.

**Comment by pipelka** [comment]
You can try to revert ea2fa0f.

**Comment by tunip** [comment]
ea2fa0f do not want compile.
 
```
CXX src/epg/epghandler.cpp
src/epg/epghandler.cpp: In member function 'virtual bool EpgHandler::HandleEvent(cEvent*)':
src/epg/epghandler.cpp:42:25: error: 'Channels' was not declared in this scope
     cChannel* channel = Channels.GetByChannelID(Event->ChannelID());
                         ^~~~~~~~
Makefile:131: recipe for target 'src/epg/epghandler.o' failed
make[1]: *** [src/epg/epghandler.o] Error 1
```

**Comment by pipelka** [comment]
Ok. Thanks. Will take a look ASAP.

**Comment by pipelka** [comment]
Apologize. I misunderstood you. My dev environment currently is using the "dev" branch (vdr 2.2). The "dev-vdr-2.3.x" branch isn't fully tested (I'm currently unable to test all the things involved with live DVB stream data).
For EPG testing I simply copied the EPG data from my production system. So it's possible that updating the EPG data from the DVB stream is broken.
To fully test this I have to create a docker image using vdr 2.3 (which is on my TODO) and create a container using it on my production system.
I will try to test and fix the final bits in the next couple of days.

**Comment by pipelka** [comment]
Ok. I got the vdr 2.3 version running on my production system.
No problems so far. EPG update seems to work flawlessly.
Please repull the "dev-vdr-2.3.x" branch.

**Comment by tunip** [comment]
Thanks, pulled it again and runs now quite good.

**Comment by pipelka** [comment]
Thanks. Great.
I'm preparing a new release. To follow the common branch naming for vdr plugins I will change branch names:

* master -> vdr 2.3.x sources
* vdr-2.2.x -> vdr 2.2 sources (changes to master will be backported)
* dev -> development branch based on the vdr 2.3.x sources

BTW, the vdr-plugin-robotv release will be 0.11.0 and the client version will be 0.7.0.
After the release I will start to add pending features to the client.

I'll annouce the branch naming change here when done.

**Comment by friedl82** [comment]
Great job. Back from holiday and it works. I tested live tv with fta and decrypted channels and radio channels. Also epg, playing recordings and creating timers are working as expected. Thank you.

**Comment by pipelka** [comment]
Hehe, never tested radio channels, ...
Good to know. Thanks.

**Comment by pipelka** [comment]
Ok. The branch change is done. Time to close this issue. ;-)
